site_name: Neighbors Documentation
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: 🔗
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
